/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKGPIO_H
#define _MOCKGPIO_H

#include "unity.h"
#include "unity.h"
#include "gpio.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockgpio_Init(void);
void Mockgpio_Destroy(void);
void Mockgpio_Verify(void);




#define gpio_set_ExpectAndReturn(pin, state, cmock_retval) TEST_FAIL_MESSAGE("gpio_set requires _Expect (not AndReturn)");
#define gpio_set_Expect(pin, state) gpio_set_CMockExpect(__LINE__, pin, state)
void gpio_set_CMockExpect(UNITY_LINE_TYPE cmock_line, int pin, gpio_state_t state);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
