/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockgpio.h"

static const char* CMockString_gpio_set = "gpio_set";
static const char* CMockString_pin = "pin";
static const char* CMockString_state = "state";

typedef struct _CMOCK_gpio_set_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  int Expected_pin;
  gpio_state_t Expected_state;

} CMOCK_gpio_set_CALL_INSTANCE;

static struct MockgpioInstance
{
  CMOCK_MEM_INDEX_TYPE gpio_set_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void Mockgpio_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.gpio_set_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_set);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockgpio_Init(void)
{
  Mockgpio_Destroy();
}

void Mockgpio_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void gpio_set(int pin, gpio_state_t state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_set_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_set);
  cmock_call_instance = (CMOCK_gpio_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_set_CallInstance);
  Mock.gpio_set_CallInstance = CMock_Guts_MemNext(Mock.gpio_set_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_gpio_set,CMockString_pin);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_pin, pin, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_gpio_set,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_state, &state, sizeof(gpio_state_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_gpio_set(CMOCK_gpio_set_CALL_INSTANCE* cmock_call_instance, int pin, gpio_state_t state);
void CMockExpectParameters_gpio_set(CMOCK_gpio_set_CALL_INSTANCE* cmock_call_instance, int pin, gpio_state_t state)
{
  cmock_call_instance->Expected_pin = pin;
  memcpy((void*)(&cmock_call_instance->Expected_state), (const void*)(&state),
         sizeof(gpio_state_t[sizeof(state) == sizeof(gpio_state_t) ? 1 : -1])); /* add gpio_state_t to :treat_as_array if this causes an error */
}

void gpio_set_CMockExpect(UNITY_LINE_TYPE cmock_line, int pin, gpio_state_t state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_set_CALL_INSTANCE));
  CMOCK_gpio_set_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_set_CallInstance = CMock_Guts_MemChain(Mock.gpio_set_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_gpio_set(cmock_call_instance, pin, state);
}

